\chapter{Exceptions and Backtracking}
In the first section of this chapter we will discuss exceptions as a means to deal with error
situations.  The second section will introduce  a mechanism that supports backtracking. 
This mechanism is quite similar to the exception handling in the first subsection.  Indeed, we
will see that the backtracking mechanism provided in \setlx\ is really just a special case of
exception handling.

\section{Exceptions}
If we issue the assignment
\\[0.2cm]
\hspace*{1.3cm}
\texttt{y := x + 1;}
\\[0.2cm]
while the variable \texttt{x} is undefined, \setlx\ reports the following error:
\begin{verbatim}
    Error in "y := x + 1":
    Error in "x + 1":
    'om + 1' is undefined.
\end{verbatim}
Here, evaluation of the expression \texttt{x + 1} has raised an \emph{exception} 
as it is not possible to add a number to the undefined value \texttt{om}.  This exception is then
propagated to the enclosing assignment statement. \setlx\ offers to handle exceptions like the
one described above.  The mechanism is similar as in \textsl{Java} and uses the keywords
``\texttt{try}'' and ``\texttt{catch}''.   If we have a sequence of statements
\textsl{stmntList} and we fear that 
something might go wrong with these statements, then we can put the list of statements into a
\texttt{try}/\texttt{catch}-block as follows:
\\[0.2cm]
\hspace*{1.3cm}
\texttt{try \{}
\\
\hspace*{1.8cm}
\texttt{\textsl{stmntList}}
\\
\hspace*{1.3cm}
\texttt{\} catch (e) \{ \textsl{errorCode} \}}
\\[0.2cm]
If the execution of \textsl{stmntList} executes without errors, then the
\texttt{try/catch}-block does nothing besides the execution of \textsl{stmntList}.  However, if
one of the statements in \textsl{stmntList} does raise an exception, then the execution of 
\textsl{stmntList} is aborted and instead the statement \textsl{errorCode} is executed.

Typically, exception handling is necessary when  processing user input.  Consider the program
shown in Figure \ref{fig:bisection-exception.stlx}.  The function \texttt{findZero} implements
the bisection method which can be used to find the zero of a function.  The first argument of
\texttt{findZero} is a function $f$, while the arguments $a$ and $b$ are the left and right
boundary of the intervall where the zero of $f$ is sought.  Therefore, $a$ has to be less than
$b$.  Finally, for the bisection algorithm implemented in the function \texttt{findZero} to
work, the function $f$ needs to have a sign change in the interval $[a,b]$.  

The function \texttt{askUser} asks the user to input the function $f$ together with the left and
right boundary of the interval $[a,b]$.  The idea is that the user inputs a term describing the
function value of $f$ for a given value of $x$.  For example, in order to compute the zero of the
function
\\[0.2cm]
\hspace*{1.3cm}
$x \mapsto x*x - 2$
\\[0.2cm]
the user has to provide the string ``\texttt{x*x-2}'' as input to the \texttt{read} command in
line 3.  The string \texttt{s} that is input by the user is then converted into the string
\\[0.2cm]
\hspace*{1.3cm}
\texttt{x |-> x*x-2}
\\[0.2cm]
in line 4 and, furthermore, the resulting string is parsed and then evaluated.  In this way, the
variable \texttt{f} in line 4 will be assigned the function mapping \texttt{x} to \texttt{x*x-2}
just as if the user had written
\\[0.2cm]
\hspace*{1.3cm}
\texttt{f := x |-> x*x-2;}
\\[0.2cm]
in the command line.


\begin{figure}[!ht]
\centering
\begin{Verbatim}[ frame         = lines, 
                  framesep      = 0.3cm, 
                  firstnumber   = 1,
                  labelposition = bottomline,
                  numbers       = left,
                  numbersep     = -0.2cm,
                  xleftmargin   = 0.8cm,
                  xrightmargin  = 0.8cm,
                ]
    askUser := procedure() {
        try {
            s := read("Please enter a function: ");
            f := evalTerm(parse("x |-> " + s));
            a := read("Enter left  boundary: ");
            b := read("Enter right boundary: ");
            z := findZero(f, a, b);
            print("zero at z = $z$");
        } catch (e) {
            print(e);
            print("Please try again.\n");
            askUser();
        }
    };
    findZero := procedure(f, a, b) {
        if (a > b) {
            throw("Left boundary a has to be less than right boundary b!");   
        }
        [ fa, fb ] := [ f(a), f(b) ]; 
        if (fa * fb > 0) {
            throw("Function f has to have a sign change in [a, b]!");
        }
        while (b - a >= 10 ** -12) {
            c := 1/2 * (a + b);
            fc := f(c); 
            if ((fa < 0 && fc < 0.0) || (fa >= 0 && fc >= 0)) {
                a := c; fa := fc; 
            } else {
                b := c; fb := fc; 
            }
        }
        return 1/2 * (a + b);
    };
\end{Verbatim}
\vspace*{-0.3cm}
\caption{The bisection method for finding a zero of a function.}
\label{fig:bisection-exception.stlx}
\end{figure}
 
There are a couple of things that can go wrong with the function \texttt{askUser}.  First,
the string \texttt{s} input by the user might not be a proper function and then
we would probably get a parse error in line 4.  In this case, the function \texttt{parse}
invoked in line 4 will raise an exception. Next, if the user enters a string of the form
\\[0.2cm]
\hspace*{1.3cm}
\texttt{x ** y}
\\[0.2cm]
then, since the variable \texttt{y} is undefined, the evaluation of the function would
raise an exception when \setlx\ tries to evaluate an expression of the form
\\[0.2cm]
\hspace*{1.3cm}
\texttt{x ** om}.
\\[0.2cm]
Furthermore, either of the two conditions
\\[0.2cm]
\hspace*{1.3cm}
$a < b$ \quad or \quad $f(a) * f(b) \leq 0$
\\[0.2cm]
might be violated.  In this case, we raise an exception in either line 17 or line 21.  
Since we don't want to abort the program on the occurrence of an exception, the whole block of
code in lines 3 up to line 8 is enclosed in a \texttt{try}/\texttt{catch}-block.  In case there is
an exception, the value of this exception, which is a string containing an error message, is
caught in the variable \texttt{e} in line 9.  To continue our program, we print the error message
in line 10 and then invoke the function \texttt{askUser} recursively so that the user of
the program gets another chance.

\subsection{Different Kinds of Exceptions}
\setlx\ supports two different kinds of exceptions:
\begin{enumerate}
\item \emph{User generated} exceptions are generated by the user via a \texttt{throw} statement.
      In general, the statement
      \\[0.2cm]
      \hspace*{1.3cm}
      \texttt{throw($e$)}
      \\[0.2cm]
      raises a \emph{user generated} exception with the value $e$.
\item \emph{Language generated} exceptions are the result of error conditions arising in
      the program. 
\end{enumerate}
While all kinds of exceptions can be caught with a \texttt{catch} clause, most of the time
it is useful to distinguish between the different kinds of exceptions.  This is supported
by offering two variants of \texttt{catch}:
\begin{enumerate}
\item \texttt{catchUsr} only catches user generated exceptions.  For example, the statement
      \\[0.2cm]
      \hspace*{1.3cm}
      \texttt{try \{ throw(1); \} catchUsr(e) \{ print(e); \}}
      \\[0.2cm]
      prints the number 1, but assuming that the variable \texttt{y} is undefined, the 
      statement 
      \\[0.2cm]
      \hspace*{1.3cm}
      \texttt{try \{ x := y + 1; \} catchUsr(e) \{ print("caught " + e); \}}
      \\[0.2cm]
      will not print anything but instead the command raises an exception.
\item \texttt{catchLng} only catches language generated exceptions.  Therefore, the statement
      \\[0.2cm]
      \hspace*{1.3cm}
      \texttt{try \{ x := y + 1; \} catchLng(e) \{ print("caught " + e); \}}
      \\[0.2cm]
      prints the text
      \\[0.2cm]
      \hspace*{1.3cm}
      \texttt{caught Error: 'om + 1' is undefined.}
      \\[0.2cm]
      On the other hand,  the exception thrown in the statement
      \\[0.2cm]
      \hspace*{1.3cm}
      \texttt{try \{ throw(1); \} catchLng(e) \{ print(e); \}}
      \\[0.2cm]
      is a user generated exception and is therefore not caught.
\end{enumerate}
Being able to distinguish between user generated  and language generated exceptions is
quite valuable and we strongly advocate that user generated exceptions should only be
catched using a \texttt{catchUsr} clause.  The reason is, that a simple
\texttt{catch} clause which the user intends to catch a user generated exceptions might,
in fact, catch 
other exceptions and thus mask real errors.  In general, the \setlx\ interpreter
implements a \emph{fail fast} strategy:  Once an error is discovered, the execution of the
program is aborted.  The interpreter does a lot of effort to detect errors as early as
possible.  However, using unrestricted \texttt{catch} clauses counters this strategy and
might lead to errors that are very difficult to locate.

\section{Backtracking}
One of the distinguishing features of the programming language \textsl{Prolog} is the fact
that \textsl{Prolog} supports \emph{backtracking}.  However, on closer inspection of the
\textsl{Prolog} programs that are shown in the text books describing \textsl{Prolog}
\cite{sterling86, bratko:90} it can be seen that very few programs actually make use of
backtracking in its most general form.  Also, the personal experience of the first author, who
has programmed in \textsl{Prolog} for more than 10 years, suggests that \textsl{Prolog}
programs that use backtracking in an unrestricted fashion tend to be very hard to maintain.  
In general, it is our believe that the use of backtracking should always follow the
paradigm \emph{generate and test}:
\begin{enumerate}
\item The set of possible values should be generated by a \emph{generating function}.  
\item These values should then be tested.  If a test fails, the program backtracks
      to step 1 where the next value to be tested is generated.
\end{enumerate}
In order to support the generate and test paradigm,  \setlx\ 
implements backtracking only in a very restricted form.  Thus, we avoid the
pitfalls that accompany an unrestricted use of backtracking.
Backtracking is implemented  via the keywords ``\texttt{check}'' and
``\texttt{backtrack}''.  A block of the form
\\[0.2cm]
\hspace*{1.3cm}
\texttt{check \{} 
\\
\hspace*{1.8cm}
\textsl{stmntList}
\\
\hspace*{1.3cm}
\texttt{\}}
\\[0.2cm]
is more or less\footnote{
Technically, instead of the string \texttt{\symbol{34}fail\symbol{34}}, \setlx\ 
generates a unique exception, which can only be catched using \texttt{check}. 
}
converted into a block of the form
\\[0.2cm]
\hspace*{1.3cm}
\texttt{try \{} 
\\
\hspace*{1.8cm}
\textsl{stmntList}
\\
\hspace*{1.3cm}
\texttt{\} catch ($e$) \{}
\\
\hspace*{1.8cm}
\texttt{if ($e$ != \symbol{34}fail\symbol{34}) \{}
\\
\hspace*{2.3cm}
\texttt{throw($e$);}
\\
\hspace*{1.8cm}
\texttt{\}}
\\
\hspace*{1.3cm}
\texttt{\}}
\\[0.2cm]
while the keyword ``\texttt{backtrack}'' is translated into
``\texttt{throw(\symbol{34}fail\symbol{34})}''.   


\begin{figure}[!ht]
\centering
\begin{Verbatim}[ frame         = lines, 
                  framesep      = 0.3cm, 
                  firstnumber   = 1,
                  labelposition = bottomline,
                  numbers       = left,
                  numbersep     = -0.2cm,
                  xleftmargin   = 0.8cm,
                  xrightmargin  = 0.8cm,
                ]
    solve := procedure(l, n) { 
        if (#l == n) {
            return l;
        }
        for (x in {1 .. n} - {i : i in l}) {
            check {
                testNext(l, x);
                return solve(l + [x], n);
            } 
        }
        backtrack;
    };
    testNext := procedure(l, x) {
        m := #l;
        if (exists (i in {1 .. m} | i-l[i] == m+1-x || i+l[i] == m+1+x)) {
            backtrack;
        }
    };
\end{Verbatim}
\vspace*{-0.3cm}
\caption{Solving the 8 queens puzzle using \texttt{check} and \texttt{backtrack}.}
\label{fig:queens-nice.stlx}
\end{figure}

The program in Figure \ref{fig:queens-nice.stlx} on page
\pageref{fig:queens-nice.stlx} solves the \emph{8 queens puzzle}.  This problem asks to
position 8 queens on a chessboard such that no queen can attack another queen.  In chess, a queen
can attack all those positions that are either on the same row, on the same column, or on the
same diagonal as the queen.  The details of the program in Figure \ref{fig:queens-nice.stlx}
are as follows.
\begin{enumerate}
\item The procedure \texttt{solve} has two parameters.
      \begin{enumerate}
      \item The first parameter \texttt{l} is a list of positions of queens that
            have already been placed on the board.  It can be
            assumed that the queens already positioned in \texttt{l} 
            do not attack each other.
            
            Technically, \texttt{l} is a list on integers.
            If \texttt{l[$i$]$=k$}, then  row $i$ contains a queen in column $k$.  For example,
            \\[0.2cm]
            \hspace*{1.3cm}
            $l = \texttt{[4, 8, 1, 3, 6, 2, 7, 5]}$
            \\[0.2cm]
            is a solution of the 8 queens puzzle.  This solution is depicted in Figure
            \ref{fig:queens-solution}.

            \begin{figure}[!ht]
              \centering
              \hspace*{0.0cm}
              \vbox{\offinterlineskip
                \hrule height1pt
                \hbox{\vrule width1pt\bigchess
                  \vbox{\hbox{0Z0L0Z0Z}
                    \hbox{Z0Z0Z0ZQ}
                    \hbox{QZ0Z0Z0Z}
                    \hbox{Z0L0Z0Z0}
                    \hbox{0Z0Z0L0Z}
                    \hbox{ZQZ0Z0Z0}
                    \hbox{0Z0Z0ZQZ}
                    \hbox{Z0Z0L0Z0}}%
                  \vrule width1pt}
                \hrule height1pt}

              \caption{A solution of the 8 queens puzzle.}
              \label{fig:queens-solution}
            \end{figure}

 
      \item The second parameter \texttt{n} is the size of the board.  
      \end{enumerate}
      In order to solve the 8 queens puzzle, the procedure \texttt{solve} is called in line 26 in
      the form
      \\[0.2cm]
      \hspace*{1.3cm}
      \texttt{solve([], 8)}.
      \\[0.2cm]
      Taking the parameter \texttt{l} to be the empty list assumes that initially no queen has
      been set on the chess board.  Of course, then the assumption that the queens already
      positioned in \texttt{l} do not attack each other is trivially satisfied.
\item In line 2 it is checked, whether the list \texttt{l} already specifies the positions of
      \texttt{n} queens.  If this is the case, then because of the assumption that the queens
      specified in \texttt{l} do not attack each other, the problem is solved and therefore
      \texttt{l} is the solution and is returned.
\item Otherwise, we  find a position \texttt{x} for the next queen in line 5.  Of course,
      there is no point in trying to position the next queen into a row that has already been
      taken by one of the queens in the list \texttt{l}.  Therefore, the number of positions
      available for the next queen is given by the set
      \\[0.2cm]
      \hspace*{1.3cm}
      \texttt{\{1 ..  $\hspace*{-0.2cm}$n\} - \{i $\hspace*{-0.1cm}$: $\hspace*{-0.2cm}$i in l\}}.
      \\[0.2cm]
      Note that we had to convert the list \texttt{l} into the set 
      \texttt{\{i $\hspace*{-0.1cm}$: $\hspace*{-0.2cm}$i in l\}}
      in order to be able to subtract the positions specified in \texttt{l} from the set of all
      possible positions.
\item Once we have decided to position the next queen in row \texttt{x}, we have to 
      test whether a queen that is put into that position can be attacked by another queen
      which happens to be on the same diagonal.  This test is performed in line 7 with the help
      of the function \texttt{testNext}.
\item If this test succeeds, we add a queen in position \texttt{x} to the list \texttt{l} and
      recursively try to solve the resulting instance of the problem.
\item On the other hand, if the call to \texttt{testNext} in line 7 fails, we have to try
      the next value of \texttt{x}.  Now the function \texttt{testNext} does not return a 
      Boolean value to indicate success or failure so at this point you might well
      ask how we know that the call to check has failed.  The answer is that the function
      \texttt{testNext} includes a call to \texttt{backtrack} if it is not possible to
      place a queen in position \texttt{x}.  Technically, calling \texttt{backtrack}
      raises an exception that is caught by the \texttt{check} statement in line 6.
      After that,  the \texttt{for} loop in line 5 proceeds and picks the next
      candidate for \texttt{x}.
\item During the recursive invocation of the procedure \texttt{solve} in line 8, we might
      discover that the list \texttt{l + [x]} can not be completed into a solution of the 8
      queens puzzle.   In this case, it is the function \texttt{solve} that backtracks
      in line 11.  This happens when the \texttt{for} loop in line 5 is exhausted and we
      have not found a solution.  Then
      control  reaches line 11, where the backtrack statment  signals that the list \texttt{l}
      could not be completed into a solution to the \texttt{n} queens puzzle.
\item The function \texttt{testNext} in line 13 has two parameters:  The first parameter is the list
      of already positioned queens while the second parameter specifies the column of the next
      queen.  The function checks whether the queen specified by \texttt{x} is on the same
      diagonal as any of the queens in \texttt{l}.
      
      In order to understand the calculation in line 15 we have to realize that the
      cartesian coordinates of the queens in column \texttt{x} are 
      \\[0.2cm]
      \hspace*{1.3cm}
      $\pair(\texttt{\#l}+1, \mathtt{x})$.
      \\[0.2cm]
      Now a diagonal is specified as the equation of a line with slope either $+1$ or $-1$.
      The $i$-th  queen in \texttt{l} has the coordinates
      \\[0.2cm]
      \hspace*{1.3cm}
      $\pair(\texttt{i}, \mathtt{l[i]})$.      
      \\[0.2cm]
      Therefore, it is on the same ascending diagonal as the queen specified by \texttt{x} if
      we have
      \\[0.2cm]
      \hspace*{1.3cm}
      $\texttt{i-l[i]} = \texttt{\#l+1-x}$,
      \\[0.2cm]
      while it is one the same descending diagonal if we have.
      \\[0.2cm]
      \hspace*{1.3cm}
      $\texttt{i+l[i]} = \texttt{\#l+1+x}$.
\end{enumerate}

It is easy to change the program in Figure \ref{fig:queens-nice.stlx} such that all
solutions are completed.   Figure \ref{fig:queens-all.stlx} on page
\pageref{fig:queens-all.stlx} shows how this is done.
\begin{enumerate}
\item We have added a function \texttt{allSolutions}.  This function gets on parameter
      \texttt{n}, which is the size of the board.
      The function returns the set of all solutions of the $n$ queens puzzle.
      To do so, it first initializes the variable \texttt{all} to the empty set.
      The solutions are then collected in this set.
\item The function \texttt{solve} gets \texttt{all} as an additional parameter.
      Note that this parameter is specified in line 2 as an \texttt{rw} parameter, so 
      the value of \texttt{all} is actually changed by the procedure \texttt{solve}.
\item The important change in the implementation of \texttt{solve} is that instead of
      returning a solution,  a solution that is found is added to the set \texttt{all} in
      line 10. After that, the function \texttt{solve} backtracks to look for more
      solutions. 
\item The implementation of the function \texttt{testNext} has not changed.
\end{enumerate}
This program finds all 92 solutions to the $8$ queens puzzle.

\begin{figure}[!ht]
\centering
\begin{Verbatim}[ frame         = lines, 
                  framesep      = 0.3cm, 
                  firstnumber   = 1,
                  labelposition = bottomline,
                  numbers       = left,
                  numbersep     = -0.2cm,
                  xleftmargin   = 0.8cm,
                  xrightmargin  = 0.8cm,
                ]
    allSolutions := procedure(n) {
        all := {};
        check {
            solve([], n, all);
        }
        return all;
    };
    solve := procedure(l, n, rw all) { 
        if (#l == n) {
            all += { l };
            backtrack;
        }
        for (x in {1 .. n} - {i : i in l}) {
            check {
                testNext(l, x);
                return solve(l + [x], n, all);
            } 
        }
        backtrack;
    };
    testNext := procedure(l, x) {
        m := #l;
        if (exists (i in {1 .. m} | i-l[i] == m+1-x || i+l[i] == m+1+x)) {
            backtrack;
        }
    };
\end{Verbatim}
\vspace*{-0.3cm}
\caption{Computing all solutions of the $n$ queens puzzle.}
\label{fig:queens-all.stlx}
\end{figure}


The keyword \texttt{check} can be used with an additional optional branch.  In this case the
complete \texttt{check} block has the form
\\[0.2cm]
\hspace*{1.3cm}
\texttt{check \{} 
\\
\hspace*{1.8cm}
\textsl{stmntList}
\\
\hspace*{1.3cm}
\texttt{\} afterBacktrack \{ \textsl{body} \}}
\\[0.2cm]
Here, \textsl{body} is a list of statements that is executed if there is a call to \texttt{backtrack} in
\textsl{stmntList}.  For example, the code
\begin{verbatim}
    check { 
        print(1); 
        backtrack; 
        print(2); 
    } afterBacktrack { 
        print(3); 
    }
\end{verbatim}
prints the number 1 and 3.




%%% Local Variables: 
%%% mode: latex
%%% TeX-master: "tutorial"
%%% End: 
