package org.randoom.setlx.exceptions;

public class UnknownFunctionException extends CatchableInSetlXException {
    public UnknownFunctionException(String msg) {
        super(msg);
    }
}

